name: Run Acceptance Tests

on:
  pull_request:
    branches:
      - main 

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Run acceptance tests
        run: npm test

